[project]
name = "model3d-agent"
version = "0.1.0"
description = "Generate 3D models with coding-AI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai",
    "Pillow",
]

[tool.setuptools]
packages = ["model3d_agent", "model3d_agent.cmd"]


[tool.setuptools.package-data]
"model3d_agent" = ["prompts/*.txt"]
"model3d_agent.cmd" = ["view_chat_assets/*"]
